### ISSUE TITLE
[processor/transform] Replicate metricstransform features

### ISSUE THREAD

**Issue by gabrielgiussi** [open-telemetry/opentelemetry-collector-contrib#16223]
### Component(s)

processor/transform

### Is your feature request related to a problem? Please describe.

Replicate existing features in other providers

#### metricstransformer
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16221
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16214
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16224

### Describe the solution you'd like

Decide which features will be replicated, dropped or moved to another processor

**Comment by TylerHelmuth** [comment]
Closing since we've closed all the sub-issues.
