### ISSUE TITLE
[all][meta] Make existing sensitive configuration fields opaque

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#17273]
### Overview

As part of open-telemetry/opentelemetry-collector#6851 and with the goal of creating a system to query the Collector's configuration, the [`configopaque.String` type alias](https://pkg.go.dev/go.opentelemetry.io/collector/config/configopaque) has been added to the core Collector library to be used on fields that contain sensitive information.

To ensure that no sensitive information is leaked on existing components' configuration, we need to audit their configuration schema and change the type on sensitive fields to use `configopaque.String`.

This issue intends to list all components where such a change is needed.

To generate the initial list, I searched for instances of  "Token", "Key", "Password" and "Secret" on any file named `config.go` on this repository.

### How to make the change

Changing a field type is a breaking change and should be noted as such on the changelog. Codeowners of a given component can choose to make this change with or without a deprecation, depending on how many users a component has as a Go module:

- Without deprecation by just changing the type to `configopaque.String` and noting it as a breaking change in the changelog (see open-telemetry/opentelemetry-collector/pull/6637 for an example)
- With deprecation by creating a temporary field and deprecating the current field (see https://github.com/open-telemetry/opentelemetry-collector/pull/6470#issuecomment-1332094426 for a more detailed step by step plan)

My expectation is that for most fields we can do this without deprecation since usage of the Go API is minimal/nonexistent.

#### Receivers

- [x] [receiver/aerospike] Use configopaque for password field
- [ ] #23829
- [x] [receiver/bigip] Use configopaque for password field
- [x] #23832 
- [x] [receiver/couchdb] Use configopaque for password field
- [x] [receiver/elasticsearch] Use configopaque for password field
- [x] [receiver/jmx] Use configopaque for password, keystore_password, truststore_password fields
- [x] [receiver/mongodbatlas] Use configopaque for private_key and secret fields
- [x] [receiver/mongodb] Use configopaque for password field
- [x] [receiver/mysql] Use configopaque for password field
- [x] [receiver/nsxt] Use configopaque for password field
- [x] [receiver/podman] Use configopaque for ssh_passphrase field
- [ ] [receiver/postgresql] Use configopaque for password field
- [x] [receiver/pulsar] Use configopaque for auth::Token::Token and auth::athenz::private_key fields
- [ ] [receiver/rabbitmq] Use configopaque for password field
- [ ] [receiver/redis] Use configopaque for password field
- [ ] [receiver/riak] Use configopaque for password field
- [x] [receiver/saphana] Use configopaque for password field
- [x] [receiver/snmp] Use configopaque for auth_password and privacy_password fields
- [x] [receiver/snowflake] Use configopaque for password field
- [x] [receiver/solace] Use configopaque for password field
- [x] [receiver/vcenter] Use configopaque for password field

#### Processors

- [x] #17314

#### Exporters

- [x] [exporter/alibabacloudlogservice] Use configopaque for access_key_secret field
- [x] [exporter/azuredataexplorer] Use configopaque for application_key field
- [x] [exporter/azuremonitor] Use configopaque for instrumentation_key field
- [x] [exporter/coralogix] Use configopaque for private_key field
- [x] #17296
- [x] #17293
- [x] [exporter/elasticsearch] Use configopaque for api_key and password fields
- [x] ~~[exporter/humio] Use configopaque for traces::ingest_token field~~ (component is deprecated)
- [x] [exporter/influxdb] Use configopaque for token and password fields
- [x] [exporter/instana] Use configopaque for agent_key field
- [x] [exporter/logicmonitor] Use configopaque for apitoken::access_key fields
- [x] [exporter/logzio] Use configopaque for account_token field
- [x] [exporter/mezmo] Use configopaque for ingest_key field
- [x] [exporter/pulsar] Use configopaque for auth::Token::Token and auth::athenz::private_key fields
- [x] [exporter/sapm] Use configopaque for access_token field
- [x] #17294
- [x] #17295
- [x] [exporter/tencentcloudlogservice] Use configopaque for secret_key field 

#### Extensions

- [x] [extension/asapauth] Use configopaque for private_key field
- [x] [extension/basicauth] Use configopaque for client_auth::password field
- [x] [extension/bearertokenauth] Use configopaque for token field
- [x] [extension/oauth2clientauth] Use configopaque for client_secret field

**Comment by mx-psi** [comment]
I am working on the full list of components that need this change, consider this a draft issue until this message is hidden

**Comment by mx-psi** [comment]
This issue is big, so if you want to work on it, please pick a few components at a time and list them in a comment so that others can also work on it, thanks!

**Comment by dyladan** [comment]
i'll do the dynatrace one

**Comment by atoulme** [comment]
I’ll do the splunkhec and signalfx ones. Humio is deprecated, maybe we can pass on it.

**Comment by mx-psi** [comment]
@atoulme @dyladan I created child issues for those components and assigned them to you. I also marked humio as done since it's deprecated (thanks!)

**Comment by dyladan** [comment]
Looks like dynatrace was already done by @codeboten in https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/62da158b2565d8f6a2694d6f6922698a083f09fe https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17077

**Comment by gbbr** [comment]
Picking up processor/resourcedetectionprocessor https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17314

**Comment by gbbr** [comment]
Picking up extension/asapauthextension: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17316 / https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17317

**Comment by gbbr** [comment]
Did the rest of the extensions here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17318. I hope it's ok for them to be part of the same PR.

**Comment by gbbr** [comment]
Migrated all receivers in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17353

**Comment by gbbr** [comment]
...and the exporters are here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17354.

I think that should have covered everything now.

**Comment by MovieStoreGuy** [comment]
Hey @mx-psi , 

After reviewing https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17354, I am not certain that this would be considered a breaking change considering from the user's perspective nothing has changed. 
From a development perspective, I don't think this is a breaking change either considering that it is possible to cast back to the original string with no impact.

Is there anything I am missing that would cause this to be a breaking change?

**Comment by mx-psi** [comment]
> Is there anything I am missing that would cause this to be a breaking change?

This will not affect end-users of Collector binaries built using the Collector builder (either official or custom), but there exist programs written before changing the type that will fail to build after changing the type because of a type mismatch. This is a breaking change, and semi-official Go tooling like [`apidiff`](https://pkg.go.dev/golang.org/x/exp@v0.0.0-20230108222341-4b8118a2686a/apidiff#section-readme) would identify it as such.

I agree it is not a breaking change that would cause much pain (it's Go API only, and easy to fix), which is why I argue above that it's fine to do this in one step without deprecation, but (unless this causes significant confusion), I don't see why we should not label it as breaking when it is.

**Comment by mackjmr** [comment]
I can take over the rest ✋

**Comment by mackjmr** [comment]
All the receivers have been updated @mx-psi, I think this issue is good to close!

**Comment by mx-psi** [comment]
Thanks @mackjmr!! :rocket: :rocket:
