### ISSUE TITLE
Ensure that all codeowners are members of the OpenTelemetry organization

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#20868]
### Describe the issue you're reporting

Not all [codeowners](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/CODEOWNERS) of this repository are members of the OpenTelemetry github organization, which membership is associated with membership of the OpenTelemetry project.

The [guidelines](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#becoming-a-code-owner) enforce membership because it allows to assign and ping codeowners on issues or pull requests. Unfortunately, if you try to create an issue or assign a PR to a codeowner who is not member of OpenTelemetry, the workflow fails. I would like to fix this issue.

Going forward, I would also ideally like to make sure that we check that codeowners are members of the github organization whenever the codeowners file is touched.

The process to become a member of OpenTelemetry is straightforward. Open [this issue template](https://github.com/open-telemetry/community/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) on the [community project](https://github.com/open-telemetry/community) to get started.

I have identified a list of codeowners who are not currently members of OpenTelemetry. I will ping them in this issue below.
1. Please cross your name to indicate you have seen this message.
2. (optional) Please get in touch over Slack: I have created a slack channel for the purpose of codeowner discussions, [#otel-collector-codeowners](https://cloud-native.slack.com/archives/C053HRUP20Y). Feel free to reply here as well and provide clarifications if any information is incorrect.
3. Please work towards membership. Feel free to use 2. for any questions.
4. If I don't hear from you in the next 60 days (tentative), I will regrettably need to open a pull request to remove you from the codeowners.

* [x] open-telemetry/community/issues/1419
* [x] [@Doron-Bargo](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23390)
* [x] [@agoallikmaa](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23391)
* [x] open-telemetry/community/issues/1435
* [x] [@alexvanboxel](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23392)
* [x] #20886
* [x] [@architjugran](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23393)
* [x] open-telemetry/community/issues/1424
* [x] open-telemetry/community/issues/1422
* [x] open-telemetry/community/issues/1423
* [x] open-telemetry/community/issues/1449
* [x] [@eedorenko](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23394)
* [x] https://github.com/open-telemetry/community/issues/1446
* [x] open-telemetry/community/issues/1434
* [x] [@keep94](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23395)
* [x] open-telemetry/community/issues/1448
* [x] [@kiranmayib](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23393)
* [x] open-telemetry/community/issues/1524
* [x] [@leonsp-ai](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23396)
* [x] [@liqiangz](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23397)
* [x] open-telemetry/community/issues/1447
* [x] open-telemetry/community/issues/1420
* [x] open-telemetry/community/issues/1417
* [x] [@oded-dd](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23398)
* [x] @ofirshmuel
* [x] open-telemetry/community/issues/1421
* [x] [@pcwiese](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23399)
* [x] [@pxaws](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23400)
* [x] open-telemetry/community/issues/1495
* [x] open-telemetry/community/issues/1476
* [x] [@shaochengwang](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23401)
* [x] [@svrakitin](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23402)
* [x] [@tamir-michaeli](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23404)
* [x] [@tbarker25](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23405)
* [x] [@thepeterstone](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23395)
* [x] [@tjiuming](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23406)
* [x] open-telemetry/community/issues/1427
* [x] [@wgliang](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23407)
* [x] [@yiyang5055](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23407)
* [x] open-telemetry/community/issues/1471

Thank you and apologies for the inconvenience.

**Comment by jacobmarble** [comment]
> Please cross your name to indicate you have seen this message

I don't have edit privileges, but you may cross me off with this PR https://github.com/open-telemetry/community/issues/1446

**Comment by atoulme** [comment]
We are now at the 60 days mark. I have checked that folks who have not checked back in have not otherwise obtained membership. I will work to check if the codeowners are still listed in the repository.

**Comment by atoulme** [comment]
I have checked and all codeowners, with the exception of `@ofirshmuel`, are still listed as active codeowners.

**Comment by mx-psi** [comment]
Should we unpin this now that we have sub-issues for each component?

**Comment by TylerHelmuth** [comment]
Sure

**Comment by pxaws** [comment]
https://github.com/open-telemetry/community/issues/1612

**Comment by pcwiese** [comment]
I've been dragging my feet on this request. Could I get a couple of sponsors so I can complete my membership request? Most of my contributions are for the azuremonitorexporter and tailsampling processor.

**Comment by atoulme** [comment]
You can count on my sponsorship.

**Comment by TylerHelmuth** [comment]
I'll sponsor

**Comment by alexvanboxel** [comment]
I want to pick up my work again on the GooglePubsub receiver/exporter... I've been away for a while. But I need two persons to sponsor me toward membership. I'll mentioning some of the people I interacted it during the year(s): @mx-psi , @jrcamp , @djaglowski , @jpkrohling

My contributions are in general small, so I won't be mad if anyone don't remember me. But could someone sponsor me for membership? Thanks.

**Comment by djaglowski** [comment]
@alexvanboxel, I'm happy to sponsor you.

**Comment by jpkrohling** [comment]
I can sponsor you as well.

**Comment by alexvanboxel** [comment]
Thanks @jpkrohling and @djaglowski . I will work through all the documentation over the weekend to start the procedure.

**Comment by atoulme** [comment]
Closing as the end of this campaign. A new campaign should start for the new set of codeowners who are in allowlist.
