### ISSUE TITLE
[admin] cleanup tracker from 0.76.x release

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#21289]
### Describe the issue you're reporting

After https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21287 is merged we need to cleanup the following items:

- [x] Update `version` in `cmd/oteltestbedcol/builder-config.yaml` to be `0.76.3-dev`
- [x] Update `version` in `cmd/otelcontribcol/builder-config.yaml` to be `0.76.3-dev`
- [x] Update `Version` in `cmd/oteltestbedcol/main.go` to be `0.76.3-dev`
- [x] Update `Version` in `cmd/otelcontribcol/main.go` to be `0.76.3-dev`

feedback from https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21240
