### ISSUE TITLE
Add basic log collection capabilities

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#2264]
This is a checklist issue that captures all work that needs to be done for us to have basic log collection features based on the newly contributed https://github.com/open-telemetry/opentelemetry-log-collection codebase.

- [x] Change dependency from github.com/observiq/stanza to github.com/open-telemetry/opentelemetry-log-collection: #2273
- [x] Refactor stanzareceiver to allow splitting into separate receivers: #2265
- [x] Add filelog receiver: #2268
- [x] Make sure regex, json, timestamp, severity parser operators are supported for all log receivers. #2282 
- [x] Remove `stanzareciever`: #2321 
- [ ] Design and implement distributed persistence mechanism for log receivers #2287 
- [ ] Embed log-collection operator configurations directly into receiver configs: #2334
- [ ] Add support for collecting Kubernetes logs: #2266
- [ ] Enable k8s log collection in [Otel Helm Chart](https://github.com/open-telemetry/opentelemetry-helm-charts). 
- [ ] Add winlog receiver: #2333
- [ ] Add journald receiver: #2332
- [ ] Add syslog receiver: #2331
- [ ] Improve translation to pdata, avoid emitting entire pdata.Logs for each log record. #2330
- [ ] Add OTLP/JSON-format file log collection support.
- [ ] Move log receivers from contrib to core Collector repo and add to the core build.
- [ ] Add support for plugins / predefined formats. #2471
- [ ] Add double-star mutli-level directory glob matching to filelog receiver: #2329
- [ ] Add compressed file collection support to filelog receiver: #2328

**Comment by tigrannajaryan** [comment]
Let's use a milestone to track: https://github.com/open-telemetry/opentelemetry-collector-contrib/milestone/8
Closing the issue since it is no longer needed.
