### ISSUE TITLE
[cmd/opampsupervisor] Alpha release tracking issue

### ISSUE THREAD

**Issue by evan-bradley** [open-telemetry/opentelemetry-collector-contrib#24327]
### Component(s)

cmd/opampsupervisor

### Describe the issue you're reporting

Tracking issue for a minimally-viable release of the OpAMP Supervisor. This just tracks the required issues to release something that is considered ready for evaluation and prototyping, not necessarily something that we intend for production usage. These points are all negotiable, and I will update the issue to reflect the current consensus.

See the [design document](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/opampsupervisor/specification/README.md) for the overall approach.

**OpAMP message handling**

- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21043
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21079

**Collector process handling**
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21071
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21078
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24324

**Collector prerequisites**

- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16462

**Releasing a Supervisor binary**

- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24295
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24292
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24293

**Other**
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32455

**[Link to all open OpAMP Supervisor issues](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues?q=is%3Aopen+is%3Aissue+label%3Acmd%2Fopampsupervisor)**

I will update the prerequisite issues here as we determine changes are needed.

**Comment by jaronoff97** [comment]
@evan-bradley Now that we have i think all of the pre-reqs for the collector merged (effective config, reporting status, etc.) are we able to make some progress on these issues? I have some folks that may be interested in contributing if you have a sense which are good ones to start on.

**Comment by tigrannajaryan** [comment]
@jaronoff97 it may be easiest to start with unit tests and integration tests then continue with https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24324

**Comment by evan-bradley** [comment]
The Supervisor binary is now released, so I think we can safely say it is in alpha stability. Thanks everyone who contributed!

The binaries are available in the opentelemetry-collector-releases repo, here's an example release for v0.123.0: https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/cmd%2Fopampsupervisor%2Fv0.123.0.
