### ISSUE TITLE
[processor/transform] Move to Beta stability

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#28644]
### Component(s)

processor/transform

### Describe the solution you'd like

The transformprocessor is current Alpha stability, but, despite OTTL changing a lot, the processor itself has remained stable. I'd like to discuss what work we need to do to move the processor to Beta.

Looking over the transformprocessor issues I believe we should resolve these issues before marking Beta:
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/28892
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27830
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27407
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20773
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22743
