### ISSUE TITLE
Re-enable Windows tests disabled due to #11451

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector-contrib#28679]
### Describe the issue you're reporting

Many tests were disabled on Windows due to issue #11451 - this issue tracks re-enabling all these tests.

- [X] ./cmd/configschema/comments_test.go: fix via #28682
- [X] ./cmd/configschema/common_test.go: fix via #28682
- [X] ./cmd/configschema/configs_test.go: fix via #28682
- [X] ./cmd/configschema/docsgen/docsgen/cli_test.go: fix via #28682
- [X] ./cmd/configschema/docsgen/docsgen/template_test.go: fix via #28682
- [X] ./cmd/configschema/fields_test.go: fix via #28682
- [X] ./cmd/configschema/resolver_test.go: fix via #29343
- [ ] ./cmd/otelcontribcol/exporters_test.go
- [X] ./cmd/otelcontribcol/extensions_test.go: fix via #28682
- [X] ./cmd/otelcontribcol/processors_test.go: fix via #28682
- [ ] ./cmd/otelcontribcol/receivers_test.go
- [X] ./extension/storage/dbstorage/config_test.go: fix via #28682
- [X] ./extension/storage/dbstorage/extension_test.go: fix via #28682
