### ISSUE TITLE
[pkg/ottl] Promote OTTL to Beta Stability

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#28892]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

OTTL has seen extensive use via the transform processor, filter processor, tail sampling processor, routing processor, count connector, and routing connector.  Although there is a few items to address, breaking changes are slowing down. I believe the package is close to Beta stability.

Items to address:
  - [x] #28893
  - [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13545
  - [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22743
  - [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22744
  - [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30051
  - [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26108
  - [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27820
  - [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/28642
  - [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29017
  - [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16221
  
 This is an initial list, but not exhaustive - it may change over time.

**Comment by crobert-1** [comment]
From the [stability levels documentation](https://github.com/open-telemetry/opentelemetry-collector#beta) and referenced issues, it sounds good to me. 👍

**Comment by pavolloffay** [comment]
Is there any update on this?

**Comment by TylerHelmuth** [comment]
@edmocosta is actively working on https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29017 and has been for quite some time as it has been a hard one to solve in a backwards compatible way. This is likely the last big thing before beta.

**Comment by TylerHelmuth** [comment]
I've removed https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29016 from the beta requirements list. We will look into it at a later time.
