### ISSUE TITLE
[processor/deltatocumulative]: progress tracking

### ISSUE THREAD

**Issue by sh0rez** [open-telemetry/opentelemetry-collector-contrib#30705]
> [!IMPORTANT]
> This is strictly for progress tracking. Please do any discussion in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30479

---

- [x] **Structure PR**: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30706
- [x] **Design proposal**: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30479
- [ ] **Implementation**
  - [x] Accumulate Sums: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30707
    - [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31365
    - [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31349
  - [x] Accumulate Histograms: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33983
  - [x] Accumulate exp. Histograms:
      - [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31340
      - [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32030
  - [x] Purge stale series: 
    - [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31016
    - [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31337
    - [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31625
  - [x] Series Limit
    - [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31488
    - [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31603
  - [ ] Handle out of order samples:
    - [ ] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32958
  - [x] Instrumentation:
      - [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31363
      - [ ] Propagate request `context.Context` from `ConsumeMetrics()`
  - [ ] Lifecycle tests: <kbd>TODO</kbd>
- [ ] **Future** 
  - [ ] Analyze if global locking is a bottleneck, if so choose a more efficient data structure / sync strategy
  - [ ] Investigate horizontal scaling options, similar to [loadbalancingexporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/loadbalancingexporter/README.md)

**Comment by burnjake** [comment]
Just adding that I have a use case where we are trying to send metrics from a high number of mobile clients but our metrics backend has a hard limit on the frequency of sample ingestion (GCP, once every 5s). This means we need to aggregate before sending them which sounds like an intended use for this ;) I volunteer as tribute to help test if this would help at all.

**Comment by sh0rez** [comment]
@burnjake this is also in progress! see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29461 for details.

on a side note, please keep ideas / requests / discussions to the design issue (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30479), as this one is just for tracking progress ;)
