### ISSUE TITLE
OTTL additional converters 

### ISSUE THREAD

**Issue by michalpristas** [open-telemetry/opentelemetry-collector-contrib#31930]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

as we discussed with @evan-bradley at KubeCon we'd like to contribute to OTTL and identified some features which are missing from our point of view and we'd like to contribute them. 

i'm bringing here (hopefully) a descriptive task list with these items to discuss and find agreement which of these fit and which do not fit upstream

for those we agree to work on upstream I'd create a separate issues where we can talk specifics

### Describe the solution you'd like

_*checked are things we agreed on_

### Converters
- [x] Support for timezone, format and locale for `Time` converter
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32140
- [x] Add `Append` converter appending one or more items into an array
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32141
- [x] Add new ottl functions for renaming fields in one step: 
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31901
- [x] Allow specifying conflict strategy for `set`: 
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31808
- [ ] Missing support for loops: 
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29289
- [x] Consider `ExtractGrokPatterns` alternative to `ExtractPatterns` for better user experience
- [x] Consider `fail` conflict strategy for `merge_maps` (fail fails with error in case target field is present)
- [ ] ~~Missing converter for `MurmurHash3`~~
- [x] Missing converter for `SHA-512`
- [x] Missing converter for `MD5`
- [x] Add option to convert uri string into uri object/map
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32433
- [ ] `ParseKeyValue` Allow regex for delimiters
- [x] Add user agent converter (extracts details from the user agent string and adds this information by default under the - `user_agent`)
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32434
- [ ] Add a registered domain converter that will extract subdomain, registered_domain, top_level_domain and domain from FQDN
- [ ] Support for `join`: Accept field array for Concat or provide ConcatField
- [ ] Missing `StripHTML` converter for removing HTML tags from text
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36562
- [ ] Add `NetworkDirection` converter providing inbound/outbound direction based on source, dest and internal network fields
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36582
- [x] Add `Sort` converter sorting array value asc or desc
- [ ] OTTL converter for trimming whitespaces and other symbols specified
- [ ] `Translate` converter that converts a field to a string value based on a predefined mapping
- [ ] `Filter` converter to parse the PRI field from the front of a Syslog (RFC3164) message
- [ ] Converter to non-ASCII characters with an ASCII approximation
- [x] Add `ExtractGrokPattern` converter returning a map of values fitting parsed patterns
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32593

### Processors
- [x] Introduce GeoIp processor 
  - adds information about the geographical location of an IPv4 or IPv6 address by quering specified geoip databse (e.g GeoLite2)
  - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32663
- [ ] Introduce DNS processor
  - performs a lookup (either an A record/CNAME record lookup or a reverse lookup at the PTR record)
