### ISSUE TITLE
[pkg/ottl] [Time] Add support for format and timezone

### ISSUE THREAD

**Issue by michalpristas** [open-telemetry/opentelemetry-collector-contrib#32140]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

atm [Time](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/ottlfuncs/README.md#time) is simple and converts `string` to `time.Time` 

### Describe the solution you'd like

supporting custom `format`, `timezone` seems like a must for some of my use cases
and `locale` would be really nice to have

### Tasks
- [x] updated docs #32185 
- [x] handling timezone leveraging location support we already have in a library #32479
- [x] adding support for locale into our time library (separate issue https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32977)
- [x] exposing locale in Time converter (separate issue https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32978)

**Comment by TylerHelmuth** [comment]
@michalpristas it seems that our docs for the `Time` function need some help.  

[The `Time` function requires as the first parameter the string to be converted and in the second parameter the format of the time the string represents.](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/63eb22bf1f66d1448078bd0a85e94f6f84ac6b86/pkg/ottl/ottlfuncs/func_time.go#L14-L17)

We also should include in the `Time` function's section [these conventions](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/63eb22bf1f66d1448078bd0a85e94f6f84ac6b86/internal/coreinternal/timeutils/internal/ctimefmt/ctimefmt.go#L65-L101), as they are what let you specify the format of the time string, including timezone.

I agree that we could add support for `locale`.  I believe this would be done via an optional string parameter.

Would you like to work on this?

**Comment by michalpristas** [comment]
yes, i believe this can be split in 2 PRs, one for doc one for locale

**Comment by michalpristas** [comment]
@TylerHelmuth as go does not support localization of datetime by default, i'm considering pulling some 3rd party library. 
something like https://github.com/goodsign/monday

**Comment by TylerHelmuth** [comment]
@michalpristas The library we are using now supports it. It's the same library stanza uses.

**Comment by michalpristas** [comment]
you sure it supports locales? what i'm looking at is [internal/coreinternal/timeutils/parser.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/coreinternal/timeutils/parser.go#L44) 
as a library it supports specifying custom location which i want to leverage when handling `timezone` arg

but i'm not finding support for locales such as `it-IT` when my tool i'm observing is producing Italian logs in a form of e.g `mercoledì set 4 2024` parsing with a layout `Monday Jan 2 2006` would yield 4th September 2024

maybe i'm just looking at the wrong place

**Comment by TylerHelmuth** [comment]
You're right, I was thinking of the `timeutils.GetLocation` call handling timezone.

I agree we'd need to add a library or update `timeutils` to support this. @djaglowski how does stanza handle this?

**Comment by djaglowski** [comment]
`pkg/stanza` has a [`location` parameter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/types/timestamp.md#timestamp-parsing-parameters). This is already part of `timeutils` so this may just be a matter of exposing it through the OTTL function?

**Comment by djaglowski** [comment]
Ahh, nevermind. I was looking at time zone considerations only. I agree if we want to translate between languages we'll need to add new functionality.

**Comment by michalpristas** [comment]
thank you for looking into it, will work on adding functionality into our existing library as part of this issue

**Comment by michalpristas** [comment]
my plan here is 4 PRs then to keep them small:
- updated docs #32185 
- handling `timezone` leveraging location support we already have in a library(would `location` be better name than `timezone` i think i'm more in favor of location now)
- adding support for `locale` into our time library
- exposing `locale` in `Time` converter

**Comment by michalpristas** [comment]
I extracted work on locales into 2 separate issues #32977 and #32978
should make it easier for people to pick them up, we can close this one as it was addressed in #32479
