### ISSUE TITLE
New receiver to ingest segments (i.e. spans) from the existing X-Ray SDK

### ISSUE THREAD

**Issue by hencrice** [open-telemetry/opentelemetry-collector-contrib#329]
**Is your feature request related to a problem? Please describe.**
Not exactly a problem but the existing X-Ray SDK generates segments (i.e. spans) in a [proprietary format](https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html), so it will be nice if OT collector can ingest such telemetry.

**Describe the solution you'd like**
As for implementation, the tentative plan is to try to reuse chunks of the existing open-source X-Ray Daemon codebase, specifically:
1. Some of the existing configurations on the X-Ray daemon need to be ported to the new OT X-Ray receiver. The existing default configurations will be ported as similarly as possible so that existing X-Ray SDK users should have a pretty good getting started experience

2. The TCP HTTP proxy server that supports [centralized sampling](https://github.com/aws/aws-xray-daemon/blob/master/CHANGELOG.md#300-2018-08-28). It will be implemented in the OT X-Ray receiver. Based on an interaction on OT service Gitter, seems like there's a [precedence](https://gitter.im/open-telemetry/opentelemetry-service?at=5ee2b76324a3382d5d5fc792) already in Jaeger receiver.

3. Receive X-Ray segments on an UDP port. Obviously, the conversion from X-Ray segment -> OT format needs to happen here. Also need to hook up to the OT pipeline.
4. Depends on whether the X-Ray OT receiver is stateful or not, might need to implement graceful shutdown
5. Ensure the inner working of the X-Ray OT receiver is observable. Need to reference other OT receivers to add logs, metrics, etc.

**Describe alternatives you've considered**
N/A

**Additional context**
This is a fairly big feature so I will break it down into sub issues and documented below.

**Tasks**
- [X] #335 Identify and port existing X-Ray Daemon configurations into the OT X-Ray receiver
- [x] #430 Port X-Ray segments ingestion through UDP
- [x] #585 Implement X-Ray segments -> OT tracing data model conversion
- [x] #750 Port local TCP proxy
- [x] Need to implement graceful shutdown?
- [x] Add Integration tests of the receiver itself
- [x] #478 Enhance the observability of the receiver itself (logs, metrics, etc)
- [x] #797 Enable the receiver in top-level go.mod

**Comment by hencrice** [comment]
I'm going to start working on this

**Comment by hencrice** [comment]
One possible remaining work is to add e2e tests that covers X-Ray receiver -> mock processor -. X-Ray exporter. Resolving for now since the main implementation is done.
