### ISSUE TITLE
Weekly Report: 2024-05-26 - 2024-06-02

### ISSUE THREAD

**Issue by LucaLanziani** [open-telemetry/opentelemetry-collector-contrib#33329]
## Format
- `{CATEGORY}: {COUNT} ({CHANGE_FROM_PREVIOUS_WEEK})`
## Issues Report
<ul>

<li> New issues: 26
<details>
    <summary> Issues </summary>

- [ ] Not able to filter by nil timestamp ([#33327](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33327))
- [ ] [exporter/elasticsearch] Use a single instance of `esExporter` for all event types ([#33326](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33326))
- [ ] [prometheusremotewriteexporter] memory leak when downstream prometheus endpoint is slow/non-responsive leads to GC and "out of order" errors ([#33324](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33324))
- [ ] OpenTelemetry Collector Prometheus exporter fails with "was collected before with the same name and label values" ([#33310](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33310))
- [ ] [receiver/kafkametricsreceiver] Kafka consumer offset gives a random value instead of an actual offset ([#33309](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33309))
- [ ] [processor/resource] k8s pod metadata not insert when using loki ([#33307](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33307))
- [ ]  [receiver/dockerstats] not generating per container metrics ([#33303](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33303))
- [ ] [docs]: Is the healthcheckv2 extension actually active, or just baked into the release but not available? ([#33301](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33301))
- [ ] syslog exporter does not format structured data with multiple fields properly ([#33300](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33300))
- [ ] [processor/transform] Set attribute values using connection context ([#33288](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33288))
- [ ] Endpoint from file ([#33287](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33287))
- [ ] deltatocumulativeprocessor segfaults at stream limit ([#33285](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33285))
- [ ] Unable to export traces to elastic search engine backend ([#33294](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33294))
- [ ] [attributeprocessor] How to create a new span attribute from span's resource attribute ([#33279](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33279))
- [ ] Specify a role_arn for awscloudwatchlogs exporter ([#33278](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33278))
- [ ] deltatocumulative: Number of buckets in exponential histograms should be capped ([#33277](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33277))
- [ ] MySQL Receiver expects non-existent column in information_schema ([#33271](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33271))
- [ ] Otel can't handle messages from Databricks Diagnostic Tool with Event Hubs ([#33280](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33280))
- [ ] [processor/geoip] Add GeoIP attributes provider interface ([#33269](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33269))
- [ ] Regression: Duplicate Key in JSON After #31694 ([#33264](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33264))
- [ ] filestat - not clear how to add multiple patterns in include  ([#33262](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33262))
- [ ] `kafkaexporter` - support injecting headers ([#33260](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33260))
- [ ] Weekly Report: 2024-05-21 - 2024-05-28 ([#33243](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33243))
- [ ] Enabling WAL is not exporting metrics to Mimir backend using Prometheus remote write exporter ([#33238](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33238))
- [ ] Prometheus Metrics export failed ([#33235](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33235))
- [ ] [exporter/kafka] Add an ability to partition logs based on resource tags ([#33229](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33229))
</details>
</li>

<li> Issues needing triage: 131
<details>
    <summary> Issues </summary>

- [ ] [prometheusremotewriteexporter] memory leak when downstream prometheus endpoint is slow/non-responsive leads to GC and "out of order" errors ([#33324](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33324))
- [ ] OpenTelemetry Collector Prometheus exporter fails with "was collected before with the same name and label values" ([#33310](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33310))
- [ ] [receiver/kafkametricsreceiver] Kafka consumer offset gives a random value instead of an actual offset ([#33309](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33309))
- [ ]  [receiver/dockerstats] not generating per container metrics ([#33303](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33303))
- [ ] syslog exporter does not format structured data with multiple fields properly ([#33300](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33300))
- [ ] Endpoint from file ([#33287](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33287))
- [ ] Unable to export traces to elastic search engine backend ([#33294](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33294))
- [ ] Specify a role_arn for awscloudwatchlogs exporter ([#33278](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33278))
- [ ] `kafkaexporter` - support injecting headers ([#33260](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33260))
- [ ] Enabling WAL is not exporting metrics to Mimir backend using Prometheus remote write exporter ([#33238](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33238))
- [ ] Prometheus Metrics export failed ([#33235](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33235))
- [ ] New component: eG Innovations Telemetry Exporter ([#33219](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33219))
- [ ] New component: X.509 Certificate Monitoring ([#33215](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33215))
- [ ] The `Source`  property seems to be the wrong one for mapping client IP to ([#33210](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33210))
- [ ] [AWS components] aws-sdk-go v1 usage should be upgraded to v2 ([#33208](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33208))
- [ ] [receiver/kafka]: support receiving from multiple topics ([#33204](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33204))
- [ ] [exporter/datadog] invalid api token causes failure when using logs agent exporter ([#33195](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33195))
- [ ] testbed not working with transform processor in config ([#33193](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33193))
- [ ] experimental_metricsgeneration divide calculation is not correct ([#33179](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33179))
- [ ] [exporter/elasticsearch] Bulk indexer error: an id must be provided if version type or value are set ([#33139](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33139))
- [ ] Replace the `RemoteWriteQueue` and `WAL` with the exporterhelper queue (sending_queue) in Prometheusremotewriteexporter ([#33137](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33137))
- [ ] [Spanmetrics Connector] sometimes counter-type metrics grow exponentially. ([#33136](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33136))
- [ ] azureblobreceiver not reading the logs & traces ([#33132](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33132))
- [ ] Getting ERROR Could not get bootstrap info from the Collector: collector's OpAMP client never connected to the Supervisor ([#33129](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33129))
- [ ] [exporter/prometheus] Allow setting custom "job" and "instance" attributes ([#33118](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33118))
- [ ] Access to journal files running in container on k8s ([#33104](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33104))
- [ ] [exporter/splunkhec] Integration test failing: HTTP response to HTTPS client ([#33097](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33097))
- [ ] Keep aws cloudwatch metadata ([#33080](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33080))
- [ ] OpenTelemetry Contrib  using Mongodbatlasreceiver prompts "server busy" ([#33024](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33024))
- [ ] [receiver/filestats] Size of folder should reflect actual used bytes of the folder containing files similar to `du` ([#33016](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33016))
- [ ] Add support for Windows Authentication for direct connection to SQL Server instance ([#32986](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32986))
- [ ] Otel Processor metric filter is not working as expected ([#32982](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32982))
- [ ] [extension/k8sobserver] ingress ressources ([#32971](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32971))
- [ ] jmx receiver autodiscover targets in kubernetes? ([#32965](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32965))
- [ ] Windows event_data format is difficult to consume ([#32952](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32952))
- [ ] [pkg/ottl] Split ConvertCase function to explicit functions for each case ([#32942](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32942))
- [ ] I would like to ask if there are any official plans to support the RocketMQ receiver? ([#32938](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32938))
- [ ] [exporter/prometheusremotewriteexporter] Allow to set batch_send_deadline ([#32891](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32891))
- [ ] Why trace clickhouse exporter always shows "Exporting Failed: The column Timestamp is not present" ([#32886](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32886))
- [ ] Easy scaling when using non push based receivers ([#32869](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32869))
- [ ] system.cpu.time and system.cpu.utilization metrics seem incorrect when running collector on a Windows operating system ([#32867](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32867))
- [ ] Add support for DigitalOcean droplets to resourcedetetorprocessor ([#32858](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32858))
- [ ] [CI/CD] Cache Go step failing on windows ([#32844](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32844))
- [ ] Proposal: Adaptive Filter Processor ([#32841](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32841))
- [ ] [prometheusreceiver] metric datapoints attributed to two different ServiceMonitor jobs ([#32828](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32828))
- [ ] spanmetrics: Add a default namespace ([#32818](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32818))
- [ ] Allow setting of storage policy for clickhouse exporter ([#32816](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32816))
- [ ] New component: Trace Reshape Processor ([#32796](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32796))
- [ ] Flaky test: sumologicextension/extension.go:810 ([#32785](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32785))
- [ ] Enable exporters as Azure Log Analytics Workspace or Azure Application Insight. ([#32765](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32765))
- [ ] exporter/clickhouse cannot operate without `create database`, `create table` permissions ([#32738](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32738))
- [ ] Exporter/clickhouse support for  distributed table ([#32736](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32736))
- [ ] [receiver/kafka]: Replace "topic" setting by "traces_topic", "logs_topic" and "metrics_topic" ([#32735](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32735))
- [ ] How should we handle imports of time/tzdata by dependencies? ([#32688](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32688))
- [ ] [pkg/translator/prometheusremotewrite] Introduce API based around hash based metrics identifiers ([#32666](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32666))
- [ ] New component: processor for external/remote processing ([#32664](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32664))
- [ ] [receiver/mongodb] Failing integration test due to timeout ([#32658](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32658))
- [ ] [receiver/elasticsearch] TestIntegration test times out intermittently ([#32656](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32656))
- [ ] [receiver/kafka] Ability to provide custom encoders ([#32633](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32633))
- [ ] [extension/oauth2clientauth] Enable dynamically reading ClientID and ClientSecret from command ([#32602](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32602))
- [ ] [k8sattributesprocessor]  The sources.from types add enum metric_attribute ([#32596](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32596))
- [ ] otlpjsonfilereceiver: support compressed files from fileexporter ([#32565](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32565))
- [ ] Prometheus receiver fails on federate endpoint when job and instance labels are missing ([#32555](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32555))
- [ ] [exporter/prometheus] does not show metrics from otlp receiver ([#32552](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32552))
- [ ] sqlqueryreceiver - create one metric per row returned ([#32546](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32546))
- [ ] [receiver/hostmetrics] Process scrape integration test failing ([#32536](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32536))
- [ ] [exporter/clickhouse] Integration test hits a panic ([#32530](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32530))
- [ ] [exporter/prometheus] Support Prometheus Created Timestamp feature ([#32521](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32521))
- [ ] prometheus exporter precision error with histogram bucket  ([#32514](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32514))
- [ ] [exporter/prometheusremotewrite] Permanent error: Permanent error: context deadline exceeded ([#32511](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32511))
- [ ] [receiver/chronyreceiver] Receiver is not scraping dial unixgram /var/run/chrony/chronyd.sock ([#32487](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32487))
- [ ] Resource attribute "service.instance.id" is converted to label "instance", conflicting with auto-generated prometheus label ([#32484](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32484))
- [ ] loadbalancingexporter makes the collector accept data to produce a reject otelcol_receiver_refused_spans ([#32482](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32482))
- [ ] [azuremonitorexporter] Duplicate logs on Kubernetes ([#32480](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32480))
- [ ] Collector fails to restart with persistent queue and health check enabled ([#32456](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32456))
- [ ] [CI] Unit tests are failing due to timeout for setup-go ([#32445](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32445))
- [ ] New component: DNS Cache Extension for OpenTelemetry ([#32410](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32410))
- [ ] [receiver/googlecloudspanner] Test TestItemCardinalityFilter_Filter fails intermittently on Windows runs ([#32397](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32397))
- [ ] [connector/spanmetrics] Test TestConnectorConsumeTracesExpiredMetrics fails intermittently on actuated ARM runners ([#32395](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32395))
- [ ] error encoding and sending metric family: write tcp 172.31.204.123:8889->172.31.42.221:60282: write: broken pipe ([#32371](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32371))
- [ ] Support SNMP Traps in snmp receiver ([#32358](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32358))
- [ ] Custom Sampler ([#32353](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32353))
- [ ] Unable to get instance details through mongodb receiver ([#32350](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32350))
- [ ] [statsdreceiver] fail to parse payloads with empty tag data ([#32337](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32337))
- [ ] [statsdreceiver] no metamonitoring information emitted by receiver ([#32335](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32335))
- [ ] [receiver/windowsperfcounters] When collecting instances with multiple matches, data is lost ([#32319](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32319))
- [ ] [exporter/clickhouse] Integration test failing due to time out ([#32275](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32275))
- [ ] Why Does The Kafka Exporter's Raw Marshaler Marshal Everything Except Raw Bytes To JSON? ([#32237](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32237))
- [ ] the metric of target_info has too mach labels that i not need  ([#32235](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32235))
- [ ] [receiver/awscloudwatch] Missing log stream events ([#32231](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32231))
- [ ] [Hostmetrics Receiver] Add read and write character values to the process scraper  ([#32218](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32218))
- [ ] [receiver/Prometheus] inconsistent timestamps on metric points error  ([#32186](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32186))
- [ ] Azure monitor exporter authentication ([#32163](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32163))
- [ ] Failed to connect to opensearch in TLS mode ([#32139](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32139))
- [ ]  Update module github.com/kineticadb/kinetica-api-go to v0.0.4 breaks tests ([#32115](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32115))
- [ ] Optimize OTEL agent memory usage ([#32035](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32035))
- [ ] awskinesisexporter: Add support for partitioning records by traceId ([#32027](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32027))
- [ ] [receiver/datadog] Grafana Cloud Operations table is not detailed by endpoint ([#31938](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31938))
- [ ] [receiver/httpcheck] Support log pipeline for httpcheck events ([#31933](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31933))
- [ ] [Makefile.Common] Files under submodule will cause the result of `all-pkgs` to be empty. ([#31928](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31928))
- [ ] Jaeger UI SPM spanmetrics not working in 0.95.0 ([#31922](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31922))
- [ ] prometheusremotewrite context deadline exceeded ([#31910](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31910))
- [ ] [connector/servicegraph] New labels for service disambiguation and identification ([#31889](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31889))
- [ ] [exporter/prometheus] Wait for final scrape during collector shutdown ([#31887](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31887))
- [ ] [connector/spanmetrics] Add maximum span duration metric ([#31885](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31885))
- [ ] Azure Monitor Exporter Role Name differences ([#31884](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31884))
- [ ] splunkhecexporter field extraction truncates at 1000 characters ([#31817](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31817))
- [ ] Support cross account log collection through IAM roles ([#31810](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31810))
- [ ] Add support for TLS in memcachedreceiver ([#31729](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31729))
- [ ] Generate gauge metrics from traces ([#31696](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31696))
- [ ] prometheus receiver: support collectd's binary network protocol ([#31546](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31546))
- [ ] Load client certificate from hardware security device with Pkcs11 protocol ([#31536](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31536))
- [ ] [receiver/awscontainerinsight] Gather instance metadata parameters from Kubernetes API when EC2 instance metadata is not accessible ([#31511](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31511))
- [ ] [exporter/file] Support setting permissions on opened files ([#31459](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31459))
- [ ] [exporter/azuremonitor] Forward net.* attributes to Application Insights ([#31438](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31438))
- [ ] Dynamic selection of log_group_name and log_stream_name in aws cloudwatch logs exporter ([#31382](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31382))
- [ ] Add Windows Service status metrics ([#31377](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31377))
- [ ] [processor/resourcedetection] AWS Lambda faas.instance and aws.log.* attributes not set ([#31359](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31359))
- [ ] [spanmetrics connector] suddenly collector pod Evicted and unexpectedly increased 'calls_total' ([#31025](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31025))
- [ ] Http semantic convention breaking changes in 1.23 ([#30935](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30935))
- [ ] Add support for Docker container health checks to the collector image ([#30798](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30798))
- [ ] Add metrics to understand cost of telemetry ([#30729](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30729))
- [ ] prometheusremotewrite exporter with histogram is causing metrics export failure due to high memory (90%)  ([#30675](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30675))
- [ ] Exporter Feature: OpenSearch Metrics ([#30556](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30556))
- [ ] Generate logs from trace pipeline ([#30459](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30459))
- [ ] [receiver/redisreceiver] Flaky cluster integration test ([#30411](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30411))
- [ ] Otel-collector-contrib with prometheus exporter missing exemplars (TraceId and SpanId) ([#30197](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30197))
- [ ] get a full list of all attributes per resource with full qualified attribute name e.g. from metadata.*, auth.* ([#30180](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30180))
- [ ] [exporter/clickhouse] exporter fails with IO timeout error under load ([#30175](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30175))
- [ ] Add 'memory request' feature ([#29347](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29347))
- [ ] Rogue Parent ID generate in Azure Container App ([#28870](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/28870))
</details>
</li>

<li> Issues ready to merge: 2
<details>
    <summary> Issues </summary>

- [ ] [exporter/kafkaexporter] added an option to disable kerberos PA-FX-FAST negotiation ([#33086](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33086))
- [ ] Add integration test for rabbitmq exporter ([#32856](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32856))
</details>
</li>

<li> Issues needing sponsorship: 21
<details>
    <summary> Issues </summary>

- [ ] New component: eG Innovations Telemetry Exporter ([#33219](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33219))
- [ ] New component: X.509 Certificate Monitoring ([#33215](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33215))
- [ ] I would like to ask if there are any official plans to support the RocketMQ receiver? ([#32938](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32938))
- [ ] Proposal: Adaptive Filter Processor ([#32841](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32841))
- [ ] New component: AWS ApplicationSignals Processor ([#32808](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32808))
- [ ] New component: Trace Reshape Processor ([#32796](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32796))
- [ ] New component: netflow receiver ([#32732](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32732))
- [ ] New component: processor for external/remote processing ([#32664](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32664))
- [ ] New component: DNS Cache Extension for OpenTelemetry ([#32410](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32410))
- [ ] slurm processor ([#32312](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32312))
- [ ] Data Quality Connector ([#31909](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31909))
- [ ] New component: DaprExporter and DaprReceiver ([#31634](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31634))
- [ ] New component: migratecheckpoint ([#30656](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30656))
- [ ] New component: Fluent Forward Exporter ([#29413](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29413))
- [ ] New component: IPFIX Lookup ([#28692](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/28692))
- [ ] New component: AWS Lambda Telemetry API Receiver ([#26254](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26254))
- [ ] New component: Vault Config Source ([#24173](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24173))
- [ ] New component: Log-based metrics processor ([#18269](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18269))
- [ ] New component: crash report extension ([#16598](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16598))
- [ ] New component: AWS CloudWatch metrics receiver  ([#15667](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/15667))
- [ ] New component: prometheus remotewrite receiver ([#14751](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14751))
</details>
</li>

<li> New issues needing sponsorship: 0
</li>
</ul>

## Components Report
<ul>

<li> deprecated: 1
<details>
    <summary> Components </summary>

- [ ] instanaexporter: {"deprecated":["traces"]}
</details>
</li>

<li> unmaintained: 1
<details>
    <summary> Components </summary>

- [ ] skywalkingexporter: {"unmaintained":["metrics","logs"]}
</details>
</li>
</ul>
