### ISSUE TITLE
[receiver/vcenter] Additional metrics for vCenter receiver

### ISSUE THREAD

**Issue by BominRahmani** [open-telemetry/opentelemetry-collector-contrib#33607]
### Component(s)

receiver/vcenter

### Is your feature request related to a problem? Please describe.

There are various metrics that we don't currently capture or could capture at a higher level.

### Describe the solution you'd like

These metrics can most aptly be categorized under three categories:

### Datacenter
```
- vcenter.datacenter.cluster.count                 status={red/green/yellow}
- vcenter.datacenter.vm.count                      status={red/green/yellow} power_state={on/off/suspended}
- vcenter.datacenter.datastore.count               status={red/green/yellow}
- vcenter.datacenter.host.count                    status={red/green/yellow} power_state={on/off}
- vcenter.datacenter.disk.space                    disk_state={available/used}
- vcenter.datacenter.cpu.limit
- vcenter.datacenter.memory.limit
```

Some of these proposed metrics may resemble existing ones, such as `vcenter.datacenter.vm.count`, which is similar to the currently captured `vcenter.cluster.vm.count`. However, the proposed metric aggregates through these alongside other vm's that may exist outside a cluster level. In effect providing a total/aggregated look into how many vms exist under that datacenter.

### Host
```
- vcenter.host.network.packet.drop.rate    direction={transmitted/received}
- vcenter.host.cpu.capacity                reserved={true/false}
```

### Resource pool
```
- vcenter.resource_pool.memory.swapped
- vcenter.resource_pool.memory.ballooned
- vcenter.resource_pool.memory.private
- vcenter.resource_pool.memory.shared
- vcenter.resource_pool.memory.usage          (currently exists: alteration -> type={guest/host/overhead})
```
### Virtual machine
```
- vcenter.vm.cpu.readiness
```
If approved, I can split these enhancements out into 4 separate PR's.
- [x] Add Datacenter metrics #33933
- [x] Add Host metrics #33646
- [x] Add Resource pool metrics #33741
- [x] Add Virtual machine metrics #33608

**Comment by crobert-1** [comment]
_Removing `needs triage` based upon code owner responding 👍 to this issue._
