### ISSUE TITLE
[Tracker Issue] Review public API of components

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#4055]
This is a meta issue to track the review of the different components public API before we hit GA.

The proposed 'VERSIONING.md' document for `opentelemetry-collector` and `opentelemetry-collector-contrib` on open-telemetry/opentelemetry-collector#3476 implies that components in these repositories need to have a stable public Go API.

Any methods, constants, structs, fields, interfaces or functions that are not meant to be public should be unexported and
any packages that are private should be moved to an `internal` folder. You can have a look at the
[documentation page for each component](https://pkg.go.dev/github.com/open-telemetry/opentelemetry-collector-contrib/) to check what is public in the latest version of the component.

At least the `NewFactory` method and the configuration struct must be part of the public API.

## Exporters

- [ ] #4329
- [x] #4079
- [x] #4075
- [x] #4076
- [ ] #4330
- [ ] #4331
- [x] #4056
- [x] #4332
- [ ] #4333
- [ ] #4334
- [ ] #4335
- [x] #4336
- [ ] #4337
- [x] #4083
- [ ] #4338
- [x] #4084
- [x] #4339
- [x] #4340
- [x] #4341
- [x] #4061
- [ ] Review public API for `sentryexporter`
- [x] #4059
- [x] #4060
- [ ] Review public API for `stackdriverexporter`
- [ ] Review public API for `googlecloudexporter`
- [ ] Review public API for `sumologicexporter`
- [ ] Review public API for `uptraceexporter`
- [ ] Review public API for `googlecloudpubsubexporter`
- [x] #4057

## Processors

- [ ] Review public API for `groupbyattrsprocessor`
- [x] #4086
- [x] #7158
- [ ] Review public API for `metricstransformprocessor`
- [x] #4207
- [x] #4087
- [x] #4090
- [x] #4088

## Receivers

- [x] #4078
- [x] #4080
- [x] #4077
- [ ] Review public API for `carbonreceiver`
- [ ] Review public API for `collectdreceiver`
- [ ] Review public API for `dockerstatsreceiver`
- [ ] Review public API for `dotnetdiagnosticsreceiver`
- [x] #4068
- [x] #4066
- [x] #4067
- [ ] Review public API for `prometheusexecreceiver`
- [x] #4069
- [ ] Review public API for `redisreceiver`
- [x] #4063
- [x] #4062
- [x] #4065
- [x] #4064
- [x] ~~Review public API for `filelogreceiver`~~(logs only)
- [ ] Review public API for `statsdreceiver`
- [ ] Review public API for `wavefrontreceiver`
- [ ] Review public API for `windowsperfcountersreceiver`
- [ ] Review public API for `googlecloudpubsubreceiver`
- [x] ~~Review public API for `fluentforwardreceiver`~~ (logs only)
- [ ] Review public API for `influxdbreceiver`
- [x] #4202
- [ ] Review public API for `memcachedreceiver`
- [ ] Review public API for `nginxreceiver`
- [X] ~~Review public API for `syslogreceiver`~~ (logs only)
- [ ] Review public API for `zookeeperreceiver`
- [x] ~~Review public API for `tcplogreceiver`~~ (logs only, alpha)
- [x] ~~Review public API for `udplogreceiver`~~ (logs only, alpha)

## Others

- [ ] Review public API for `extension/httpforwarder`
- [ ] Review public API for `extension/observer`
- [x] #4085

**Comment by mx-psi** [comment]
Pinging @asuresh4, @anuraaga, @jpkrohling, @pmcollins, @owais and @jrcamp since you are mentioned 5 or more times on the CODEOWNERS. Could you check the components you own and either create a new issue for them if work needs to be done or mark them as done (by editing the list if you can or by commenting if you can't)? Thanks!

**Comment by mx-psi** [comment]
I am going to close this and related sub-issues as a wontfix; while the issue is still applicable I think it's not really actionable in this state, and instead I believe the right path is to mark this as a required item for a component to be marked as stable and leave enforcement up to reviewers on the stabilization PR
