### ISSUE TITLE
New receiver to collect metrics from Amazon ECS Task Metadata Endpoint

### ISSUE THREAD

**Issue by hossain-rayhan** [open-telemetry/opentelemetry-collector-contrib#457]
**Is your feature request related to a problem? Please describe.**
Not exactly. It's a new feature request. The Amazon ECS container agent provides a method to retrieve various task metadata and Docker stats. This is referred to as the [task metadata endpoint](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint.html). It would be great if we write an OT receiver to collect these metrics. 

**Describe the solution you'd like**
As a rough implementation plan, we will have a standard OpenTelemetry receiver which follows and supports the guidelines as other receivers. A rest-client will be needed to read data from ECS task metadata endpoint. In the beginning, user will have the option to set metrics `collection_interval` via the config file. After collecting raw data from endpoint, receiver will convert it in OT format and pass it down to the next consumer of OT pipeline. If needed, it should implement the graceful shutdown mechanism. 

**Describe alternatives you've considered**
N/A

**Additional context**
This is a fairly big feature. So, I will break it down into sub issues as below. 

**Tasks**

- [ ] #458 AWS ECS container metrics receiver: create  receiver skeleton 
- [ ] AWS ECS container metrics receiver: read metadata and stats from endpoint
- [ ] AWS ECS container metrics receiver: convert cpu stats to OT metrics
- [ ] AWS ECS container metrics receiver: convert memory stats to OT metrics
- [ ] AWS ECS container metrics receiver: convert network stats to OT metrics
- [ ] AWS ECS container metrics receiver: convert disk stats to OT metrics
- [ ] AWS ECS container metrics receiver: support task/container level metadata and metrics
- [ ] AWS ECS container metrics receiver: graceful shutdown

**Comment by hossain-rayhan** [comment]
I am working on this.

**Comment by hossain-rayhan** [comment]
Codes are merged. Closing this.

**Comment by rgarcia** [comment]
Is there a way to convert metric attributes to span resource attributes? Trying to configure the collector to pull in ECS metadata like task IDs and put them into traces...

**Comment by je-al** [comment]
Or to use the properties elsewhere? e.g. in the self scrapped internal metrics from the collector...
